### ISSUE TITLE
Fullstack project review

### ISSUE THREAD

**Issue by ShootingStar91** [elessartech/northwind-dashboard#1]
### Fullstack practice project review

This is the review for your fullstack project. It may contain suggestions for improvement, but you do not have to implement those in order to get the credits for your project.

### What I did

+ Attempted to login with wrong credentials
+ Logged in with correct credentials
+ Viewed the orders
+ Filtered orders
+ Viewed single order details
+ Downloaded CSV of a single order
+ Viewed statistics
+ Logged out

### Feedback on the project

+ The project looks great and is very polished in terms of UI and UX. The loading icon, error notification on wrong login, hover-animations on statistics page, and other details are crafted with care
+ The statistics page provides various smart and useful ways to view the orders data. Very nice!
+ Mobile responsivity works well
+ The orders page has the scroll bar hidden. There are hundreds of orders loaded without filtering, I wonder if displaying all of them is useful, when scrolling is clearly not meant to be done. Makes me wonder if the filtering should be a search instead. Or perhaps paging should be useful. Not sure, but loading 700 orders might not make sense.

### Feedback on the code

+ The backend code is simple and well-organized. Also tested which is good
+ Good utilization of Typescript
+ Good use of libraries such as styled components and Redux
+ The frontend is generally good and well-organized React.
+ In the [login page](https://github.com/elessartech/northwind-dashboard/blob/master/frontend/src/HomePage/index.tsx), the useEffect-hook is used in a rather convoluted way. A state is holding the info on whether the login button is pressed, which then triggers useEffect. I'd recommend simply making a login function which is triggered by the onClick directly. The useEffect can still be used to read the localStorage for existing login on first render, for example.

The application feels professional and implements all the features in a usable and polished manner. While the app does not allow creating or editing data, the pretty UI and rich ways of displaying data makes up for it. The code is well-written and implements the features efficiently. Very good job!

**Comment by elessartech** [comment]
Thank you for the feedback🙏
